name: ASP.NET Core CI/CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

    # ==================================================
    # 1. CHECKOUT
    # ==================================================

    - name: Checkout Repository
      uses: actions/checkout@v4


    # ==================================================
    # 2. SETUP .NET
    # ==================================================

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'


    # ==================================================
    # 3. RESTORE
    # ==================================================

    - name: Restore NuGet Packages
      run: dotnet restore


    # ==================================================
    # 4. BUILD
    # ==================================================

    - name: Build Application
      run: dotnet build --configuration Release --no-restore


    # ==================================================
    # 5. PUBLISH
    # ==================================================

    - name: Publish Application
      run: |
            dotnet publish \
            --configuration Release \
            --no-build \
            --output ./publish


    # ==================================================
    # 6. DEPLOY DIRECTLY TO SERVER
    # No GitHub Artifact
    # ==================================================

    - name: Copy Files To Server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}

        source: "./publish/*"

        target: "/root/Ecoex/Projects/Ecoex_Academy_AdminPanel/Api/Publish"

        overwrite: true
        strip_components: 1


    # ==================================================
    # 7. RESTART ASP.NET CORE SERVICE
    # ==================================================

    - name: Restart ASP.NET Core Service
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}

        script: |

          echo "Restarting Ecoex Academy API..."

          systemctl restart ecoeex-academy-api

          echo "Checking service status..."

          systemctl status ecoeex-academy-api --no-pager

          echo "Deployment completed successfully."
